title: Sachin | Portfolio
description: Personal portfolio showcasing skills, experience, and projects.
author: Sachin
email: sachin.sharma.dev@outlook.com

theme: minima

baseurl: "/sachin-sharma-portfolio"
url: "https://srma4tech.github.io"

markdown: kramdown

plugins:
  - jekyll-feed

exclude:
  - README.md
