title: Sachin Sharma | Portfolio
description: Software Engineer and AEM Developer showcasing enterprise-grade projects, skills, and experience.
author: Sachin Sharma

url: "https://srma4tech.github.io"
baseurl: "/sachin-sharma-portfolio"

theme: minima

markdown: kramdown

plugins:
  - jekyll-feed

exclude:
  - README.md
